### ISSUE TITLE
CGAL_StraightSkeleton_Wrapper.dll is missing

### ISSUE THREAD

**Issue by caglaraydin** [martindevans/CGAL_StraightSkeleton_Wrapper#1]
When I try to build it on VS2015 it states that the dll is missing. Is there anyway I can get that dll file?

**Comment by martindevans** [comment]
Which DLL are you missing?

There's a good chance your problem is caused by using VS2015. As the readme says:

> Build process depends on using the correct compiler, that's v12 (VS2013)

**Comment by caglaraydin** [comment]
CGAL_StraightSkeleton_Wrapper.dll is missing

**Comment by martindevans** [comment]
Ah, well that's the output at the end of the whole build process. Literally anything could have gone wrong to cause that!

You'll have to tell me a little more about the steps you've taken to get to this point :)

**Comment by caglaraydin** [comment]
I just clicked on build button, nothing more. Are you able to build it currently?

**Comment by martindevans** [comment]
> Are you able to build it currently?

I could about six months ago, and nothing significant has changed since then in my setup. However I'm not going to try because the build process is rather complex!

It sounds like you haven't followed the instructions in the [readme](https://github.com/martindevans/CGAL_StraightSkeleton_Wrapper/blob/master/readme.md). Before building the wrapper you need to to run a completely independent build step for boost and then CGAL.

**Comment by caglaraydin** [comment]
I will try again and update you. I may have done sth wrong.

**Comment by caglaraydin** [comment]
So I did step by step installation according to the readme file. Everything was acting perfect until vs2013 gave an error which stated that "error C1083: Cannot open include file: 'CGAL/compiler_config.h': No such file or directory"

**Comment by martindevans** [comment]
That's odd. I just did a search through the entire codebase and it doesn't mention compiler_config.h anywhere. Which file does this error come from?

Have you fully completed the guide to install CGAL (http://doc.cgal.org/latest/Manual/installation.html)? Particularly the cmake/cmake gui bit. That says it:

> dynamically generates a compiler_config.h file

So if it's missing, I guess something went wrong with your initial cmake configuration.

**Comment by caglaraydin** [comment]
Which CMake version were you using by the time? I'm trying to configure it and it gives error below;

`CMake Warning at C:/Program Files/CMake/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.6/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  cmake/modules/CGAL_SetupBoost.cmake:6 (find_package)
  cmake/modules/CGAL_SetupDependencies.cmake:85 (include)
  CMakeLists.txt:649 (include)`

**Comment by hjqcalm** [comment]
When I directly used the CGAL_StraightSkeleton_Dotnet published in windows10/vs2019/NuGet, and I ran code of ConsoleTest/Program.cs, a runtime exception was thrown, which is "System.DllNotFoundException: Can not Load DLL CGAL_StraightSkeleton_Wrapper". Can I ask you for advice? Thank you for your reply.
![1](https://user-images.githubusercontent.com/45378516/212013872-b7f839b1-d6a0-4bcd-9a2f-339f609db5f7.png)
![2](https://user-images.githubusercontent.com/45378516/212013880-c0eafd81-f802-4668-a55e-b01f025b8c00.png)

**Comment by hjqcalm** [comment]
I copied all the dlls downloaded by NuGet to the directory where the exe is located (under the debug directory), but still error will be reported.
![3](https://user-images.githubusercontent.com/45378516/212014494-0b2c2adb-5bbb-47d1-9621-233039edf354.png)
![3-1](https://user-images.githubusercontent.com/45378516/212014504-2f4c93c0-9a3f-4e86-b46a-e900aea3388b.png)

**Comment by hjqcalm** [comment]
Considering there may be a problem with "Solution Platform" of this project, I set the value to "x86" instead of "Any CPU", and I copied all the dlls downloaded by NuGet to the directory "bin\x86\Debug", including "CGAL_StraightSkeleton_Wrapper.dll", but the exception was still thrown.
![4](https://user-images.githubusercontent.com/45378516/212028131-5bb0bd7a-36f0-4e35-8a34-9f876f90f4bd.png)

**Comment by martindevans** [comment]
Unfortunately the `DllNotFoundException` isn't very helpful since it doesn't tell you _which_ DLL is missing. Instead it just indicates that something in the entire dependency tree is missing. In your case since you have the directly required DLLs it must be a system dependency missing.

My only guess is perhaps try installing a few older versions of the [vcredist](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) - since I worked on this project 6 years ago perhaps try the 2015 and 2017 versions.

**Comment by hjqcalm** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by martindevans** [comment]
(Deleted comment was an automated out-of-office reply)

**Comment by hjqcalm** [comment]
Thank you for your advice, I will try to older versions of the vcredist.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "martindevans/CGAL_StraightSkeleton_Wrapper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月12日(星期四) 晚上9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [martindevans/CGAL_StraightSkeleton_Wrapper] CGAL_StraightSkeleton_Wrapper.dll is missing (#1)





 
Unfortunatelt the DllNotFoundException isn't very helpful since it doesn't tell you which DLL is missing. Instead it just indicates that something in the entire dependency tree is missing. In your case since you have the directly required DLLs it must be a system dependency missing.
 
My only guess is perhaps try installing a few older versions of the vcredist - since I worked on this project 6 years ago perhaps try the 2015 and 2017 versions.
